import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useServer } from "@/lib/server-context";
import { errorMessage, serverAgent, type DomainCheck } from "@/lib/server-agent";

const tone = { Good: "#35D07F", Warning: "#FFB547", Info: "#4DA3FF", Error: "#FF5C70" } as const;
export default function ChecksScreen() {
  const colors = useColors("dark"); const { profile, configured } = useServer(); const [domain, setDomain] = useState(""); const [checks, setChecks] = useState<DomainCheck[]>([]); const [selected, setSelected] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState("Enter a domain and run live DNS checks");
  const run = async () => { if (!configured) { setNotice("Configure the server agent in Settings"); return; } if (!domain.trim()) { setNotice("Enter a domain without https://"); return; } setLoading(true); try { const result = await serverAgent.checks(profile, domain.trim()); setChecks(result.checks); setDomain(result.domain); setNotice(`Checked ${new Date(result.checkedAt).toLocaleString()}`); } catch (error) { setNotice(errorMessage(error)); } finally { setLoading(false); } };
  const warningCount = checks.filter((item) => item.status === "Warning" || item.status === "Error").length;
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled"><View style={styles.header}><View><Text style={[styles.kicker, { color: colors.muted }]}>SECURITY / DNS</Text><Text style={[styles.title, { color: colors.foreground }]}>Domain checks</Text></View><Pressable disabled={loading} onPress={run} style={({ pressed }) => [styles.iconButton, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed || loading ? 0.65 : 1 }]}><IconSymbol name="paperplane.fill" size={18} color={colors.primary} /></Pressable></View>
    <View style={[styles.inputCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><TextInput value={domain} onChangeText={setDomain} onSubmitEditing={run} placeholder="example.com" placeholderTextColor={colors.muted} autoCapitalize="none" autoCorrect={false} keyboardType="url" returnKeyType="go" style={[styles.domainInput, { color: colors.foreground }]} /><Pressable onPress={run} style={[styles.run, { backgroundColor: colors.primary }]}><Text style={{ color: "#07111B", fontWeight: "900", fontSize: 11 }}>{loading ? "CHECKING" : "RUN"}</Text></Pressable></View>
    <View style={[styles.domainCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.domainTop}><View style={{ flex: 1 }}><Text style={[styles.domain, { color: colors.foreground }]}>{domain || "No domain selected"}</Text><Text style={[styles.sub, { color: colors.muted }]}>{notice}</Text></View><View style={[styles.warning, { backgroundColor: warningCount ? "#FFB54718" : checks.length ? "#35D07F18" : "#4DA3FF18" }]}><Text style={{ color: warningCount ? "#FFB547" : checks.length ? "#35D07F" : "#4DA3FF", fontSize: 10, fontWeight: "800" }}>{checks.length ? `${warningCount} alerts` : "Waiting"}</Text></View></View><View style={[styles.summary, { borderTopColor: colors.border }]}><Text style={[styles.sub, { color: colors.muted }]}>{checks.filter((item) => item.status === "Good").length} checks passed</Text><Text style={{ color: warningCount ? "#FFB547" : "#35D07F", fontSize: 12, fontWeight: "800" }}>{warningCount ? `${warningCount} need attention` : checks.length ? "No critical issue" : "Not checked"}</Text></View></View>
    <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Mail & reputation</Text>{checks.map((item) => { const color = tone[item.status]; return <Pressable key={item.name} onPress={() => setSelected(selected === item.name ? null : item.name)} style={({ pressed }) => [styles.row, { backgroundColor: colors.surface, borderColor: selected === item.name ? color : colors.border, opacity: pressed ? 0.68 : 1 }]}><View style={[styles.checkIcon, { backgroundColor: `${color}18` }]}><IconSymbol name="paperplane.fill" size={16} color={color} /></View><Text style={[styles.name, { color: colors.foreground }]}>{item.name}</Text><View style={[styles.badge, { backgroundColor: `${color}18` }]}><View style={[styles.dot, { backgroundColor: color }]} /><Text style={{ color, fontSize: 10, fontWeight: "800" }}>{item.status}</Text></View><IconSymbol name="chevron.right" size={17} color={colors.muted} />{selected === item.name && <View style={styles.expanded}><Text selectable style={[styles.detail, { color: colors.muted }]}>{item.detail}</Text></View>}</Pressable>; })}{checks.length === 0 && <Text style={[styles.empty, { color: colors.muted }]}>Results will appear here. Nothing is simulated.</Text>}
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 32 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }, kicker: { fontSize: 11, fontWeight: "800", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "800", marginTop: 6 }, iconButton: { width: 40, height: 40, borderRadius: 13, borderWidth: 1, alignItems: "center", justifyContent: "center" }, inputCard: { minHeight: 50, borderRadius: 15, borderWidth: 1, padding: 5, paddingLeft: 14, flexDirection: "row", alignItems: "center", marginBottom: 12 }, domainInput: { flex: 1, fontSize: 13 }, run: { minHeight: 38, minWidth: 72, borderRadius: 11, alignItems: "center", justifyContent: "center" }, domainCard: { borderRadius: 19, borderWidth: 1, padding: 16, marginBottom: 23 }, domainTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 10 }, domain: { fontSize: 17, fontWeight: "800" }, sub: { fontSize: 10, lineHeight: 15, marginTop: 5 }, warning: { paddingHorizontal: 9, paddingVertical: 7, borderRadius: 10 }, summary: { borderTopWidth: 1, marginTop: 15, paddingTop: 12, flexDirection: "row", justifyContent: "space-between" }, sectionTitle: { fontSize: 16, fontWeight: "800", marginBottom: 11 }, row: { minHeight: 57, borderRadius: 15, borderWidth: 1, marginBottom: 8, padding: 11, flexDirection: "row", alignItems: "center", gap: 10, flexWrap: "wrap" }, checkIcon: { width: 32, height: 32, borderRadius: 10, alignItems: "center", justifyContent: "center" }, name: { flex: 1, fontSize: 13, fontWeight: "700" }, badge: { flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 8, paddingVertical: 6, borderRadius: 9 }, dot: { width: 5, height: 5, borderRadius: 3 }, expanded: { width: "100%", paddingLeft: 42, paddingBottom: 4 }, detail: { fontSize: 10, lineHeight: 16 }, empty: { textAlign: "center", marginTop: 30, fontSize: 11 } });
