import { useCallback, useEffect, useState } from "react";
import { Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useServer } from "@/lib/server-context";
import { errorMessage, formatBytes, serverAgent, type RemoteEntry } from "@/lib/server-agent";

export default function FilesScreen() {
  const colors = useColors("dark"); const { profile, configured } = useServer();
  const [path, setPath] = useState("."); const [entries, setEntries] = useState<RemoteEntry[]>([]); const [selected, setSelected] = useState<RemoteEntry | null>(null); const [content, setContent] = useState(""); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState("Connect the agent to browse live files");
  const load = useCallback(async (target = path) => { if (!configured) { setNotice("Configure the server agent in Settings"); return; } setLoading(true); try { const result = await serverAgent.files(profile, target); setPath(result.path); setEntries(result.entries); setSelected(null); setContent(""); setNotice(`${result.entries.length} items`); } catch (error) { setNotice(errorMessage(error)); } finally { setLoading(false); } }, [configured, path, profile]);
  useEffect(() => { load("."); }, [load]);
  const open = async (entry: RemoteEntry) => { if (entry.type === "folder") return load(entry.path); setSelected(entry); setEditing(false); setContent("Loading preview…"); try { const result = await serverAgent.readFile(profile, entry.path); setContent(result.encoding === "utf8" ? result.content : "Binary file preview is unavailable. Use the source application to download it."); } catch (error) { setContent(errorMessage(error)); } };
  const save = async () => { if (!selected) return; try { await serverAgent.writeFile(profile, selected.path, content); setEditing(false); setNotice(`${selected.name} saved atomically`); await load(path); } catch (error) { setNotice(errorMessage(error)); } };
  const remove = () => { if (!selected) return; Alert.alert("Delete item", `Delete ${selected.name}? Non-empty folders are protected.`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: async () => { try { await serverAgent.deleteEntry(profile, selected.path); await load(path); } catch (error) { setNotice(errorMessage(error)); } } }]); };
  const parent = path.replace(/\/+$/, "").split("/").slice(0, -1).join("/") || "/";
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={() => load(path)} tintColor={colors.primary} />} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">
    <View style={styles.header}><View><Text style={[styles.kicker, { color: colors.muted }]}>REMOTE STORAGE</Text><Text style={[styles.title, { color: colors.foreground }]}>Files</Text></View><Pressable onPress={() => Alert.prompt?.("New folder", "Folder name", async (name) => { if (!name) return; try { await serverAgent.mkdir(profile, `${path}/${name}`); await load(path); } catch (error) { setNotice(errorMessage(error)); } })} style={({ pressed }) => [styles.add, { backgroundColor: "#4DA3FF", opacity: pressed ? 0.75 : 1 }]}><Text style={{ fontSize: 22, color: "#07111B", lineHeight: 22 }}>+</Text></Pressable></View>
    <View style={[styles.pathBar, { backgroundColor: colors.surface, borderColor: colors.border }]}><Pressable onPress={() => load(parent)}><Text style={{ color: colors.primary, fontWeight: "900", fontSize: 16 }}>‹</Text></Pressable><IconSymbol name="paperplane.fill" size={16} color="#4DA3FF" /><Text style={[styles.path, { color: colors.foreground }]} numberOfLines={1}>{path}</Text></View>
    <View style={styles.toolbar}><Text style={[styles.sub, { color: colors.muted }]}>{notice}</Text><Pressable onPress={() => load(path)}><Text style={{ color: colors.primary, fontSize: 11, fontWeight: "800" }}>REFRESH</Text></Pressable></View>
    <View style={[styles.list, { backgroundColor: colors.surface, borderColor: colors.border }]}>{entries.map((entry, index) => { const color = entry.type === "folder" ? "#4DA3FF" : entry.name.startsWith(".") ? "#FFB547" : "#B58CFF"; return <Pressable key={entry.path} onPress={() => open(entry)} style={({ pressed }) => [styles.entry, index < entries.length - 1 && { borderBottomWidth: 1, borderBottomColor: colors.border }, pressed && { opacity: 0.65 }]}><View style={[styles.fileIcon, { backgroundColor: `${color}18` }]}><IconSymbol name={entry.type === "folder" ? "paperplane.fill" : "chevron.left.forwardslash.chevron.right"} size={18} color={color} /></View><View style={styles.flex}><Text style={[styles.fileName, { color: colors.foreground }]} numberOfLines={1}>{entry.name}</Text><Text style={[styles.sub, { color: colors.muted }]}>{entry.type === "folder" ? "Folder" : new Date(entry.modifiedAt).toLocaleString()}</Text></View><Text style={[styles.size, { color: colors.muted }]}>{entry.type === "folder" ? "—" : formatBytes(entry.size)}</Text><IconSymbol name="chevron.right" size={16} color={colors.muted} /></Pressable>; })}{!loading && entries.length === 0 && <Text style={[styles.empty, { color: colors.muted }]}>No items in this directory.</Text>}</View>
    {selected && <View style={[styles.preview, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.previewHeader}><View style={styles.flex}><Text style={[styles.kicker, { color: colors.muted }]}>LIVE FILE</Text><Text style={[styles.previewTitle, { color: colors.foreground }]} numberOfLines={1}>{selected.name}</Text></View><Pressable onPress={() => setSelected(null)}><Text style={{ color: colors.primary, fontWeight: "800", fontSize: 12 }}>CLOSE</Text></Pressable></View>{editing ? <TextInput value={content} onChangeText={setContent} multiline autoCapitalize="none" autoCorrect={false} style={[styles.editor, { color: colors.foreground, borderColor: colors.border }]} /> : <Text selectable style={[styles.code, { color: colors.foreground }]}>{content}</Text>}<View style={styles.previewActions}><Pressable onPress={editing ? save : () => setEditing(true)} style={[styles.smallAction, { backgroundColor: "#4DA3FF18" }]}><Text style={{ color: colors.primary, fontWeight: "800", fontSize: 11 }}>{editing ? "SAVE" : "EDIT"}</Text></Pressable><Pressable onPress={remove} style={[styles.smallAction, { backgroundColor: "#FF5C7018" }]}><Text style={{ color: "#FF5C70", fontWeight: "800", fontSize: 11 }}>DELETE</Text></Pressable></View></View>}
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 32 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }, kicker: { fontSize: 11, fontWeight: "800", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "800", marginTop: 6 }, add: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center" }, pathBar: { minHeight: 46, borderWidth: 1, borderRadius: 15, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 13 }, path: { flex: 1, fontSize: 12, fontFamily: "monospace" }, toolbar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 14 }, sub: { fontSize: 10 }, list: { borderRadius: 18, borderWidth: 1, paddingHorizontal: 14 }, entry: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: 11 }, fileIcon: { width: 34, height: 34, borderRadius: 11, alignItems: "center", justifyContent: "center" }, flex: { flex: 1 }, fileName: { fontSize: 13, fontWeight: "700" }, size: { fontSize: 10 }, empty: { textAlign: "center", paddingVertical: 30, fontSize: 11 }, preview: { borderRadius: 18, borderWidth: 1, marginTop: 15, padding: 15 }, previewHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, previewTitle: { fontSize: 17, fontWeight: "800", marginTop: 4 }, code: { backgroundColor: "#0B0F13", borderRadius: 12, padding: 14, fontFamily: "monospace", fontSize: 11, lineHeight: 18, marginTop: 14, maxHeight: 360 }, editor: { backgroundColor: "#0B0F13", borderRadius: 12, borderWidth: 1, padding: 14, fontFamily: "monospace", fontSize: 11, lineHeight: 18, marginTop: 14, minHeight: 260, textAlignVertical: "top" }, previewActions: { flexDirection: "row", gap: 9, marginTop: 12 }, smallAction: { flex: 1, alignItems: "center", paddingVertical: 11, borderRadius: 11 } });
