import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useServerStore } from "@/lib/server-store";
import { readServerSecret } from "@/lib/server-secrets";
import { trpc } from "@/lib/trpc";
import { downloadRemoteFile, uploadLocalFile, type TransferProgress } from "@/lib/resumable-transfer";

type Entry = { name: string; type: string; size: number; modifiedAt: number; permissions?: string };
const joinPath = (base: string, name: string) => `${base.replace(/\/$/, "")}/${name}`;

export default function FilesScreen() {
  const colors = useColors("dark");
  const { activeServer } = useServerStore();
  const [path, setPath] = useState("/");
  const [selected, setSelected] = useState<Entry | null>(null);
  const [content, setContent] = useState("");
  const [password, setPassword] = useState("");
  const [privateKey, setPrivateKey] = useState("");
  const [passphrase, setPassphrase] = useState("");
  const [showCredentials, setShowCredentials] = useState(false);
  const [transfer, setTransfer] = useState<TransferProgress | null>(null);
  const [notice, setNotice] = useState("Enter credentials to browse the server");
  const list = trpc.ssh.list.useMutation();
  const read = trpc.ssh.read.useMutation();
  const write = trpc.ssh.write.useMutation();
  const remove = trpc.ssh.delete.useMutation();
  const mkdir = trpc.ssh.mkdir.useMutation();
  const exec = trpc.ssh.exec.useMutation();

  const [otpCode, setOtpCode] = useState("");
  const [jumpPassword, setJumpPassword] = useState("");
  const [jumpPrivateKey, setJumpPrivateKey] = useState("");
  const [jumpPassphrase, setJumpPassphrase] = useState("");
  const credentials = useMemo(() => activeServer ? { host: activeServer.host, port: activeServer.port, username: activeServer.username, ...(activeServer.authMethod === "ssh-key" ? { privateKey } : { password }), ...(passphrase ? { passphrase } : {}), ...(activeServer.portKnockSequence ? { portKnockSequence: activeServer.portKnockSequence } : {}), ...(activeServer.forceKeyboardInteractive ? { forceKeyboardInteractive: true, otpCode } : {}), ...(activeServer.jumpHost?.enabled ? { jumpHost: { host: activeServer.jumpHost.host, port: activeServer.jumpHost.port, username: activeServer.jumpHost.username, ...(activeServer.jumpHost.portKnockSequence ? { portKnockSequence: activeServer.jumpHost.portKnockSequence } : {}), ...(jumpPrivateKey ? { privateKey: jumpPrivateKey, passphrase: jumpPassphrase || undefined } : { password: jumpPassword }) } } : {}) } : null, [activeServer, password, privateKey, passphrase, otpCode, jumpPassword, jumpPrivateKey, jumpPassphrase]);
  const refresh = useCallback(async () => {
    if (!credentials) return setNotice("Select a server profile first");
    if (!password && !privateKey) return setNotice("Add credentials for this session");
    try { const result = await list.mutateAsync({ credentials, path }); setNotice(`${result.length} items`); } catch (error) { setNotice(`ERROR: ${error instanceof Error ? error.message : "SFTP list failed"}`); }
  }, [credentials, list, path, password, privateKey]);
  const [entries, setEntries] = useState<Entry[]>([]);
  useEffect(() => { let cancelled = false; if (!activeServer) return; void readServerSecret(activeServer.id).then((secret) => { if (!cancelled && secret) { setPassword(secret.password ?? ""); setPrivateKey(secret.privateKey ?? "");  setJumpPassword(secret.jumpHostPassword ?? ""); setJumpPrivateKey(secret.jumpHostPrivateKey ?? ""); setJumpPassphrase(secret.jumpHostPassphrase ?? ""); } }); return () => { cancelled = true; }; }, [activeServer]);
  useEffect(() => { let cancelled = false; if (!activeServer) return; void readServerSecret(activeServer.id).then((secret) => { if (!cancelled && secret) { setPassphrase(secret.passphrase ?? ""); } }); return () => { cancelled = true; }; }, [activeServer]);
  useEffect(() => { if (credentials && (password || privateKey)) void refresh(); }, [credentials, password, privateKey, refresh]);
  useEffect(() => { if (list.data) setEntries(list.data); }, [list.data]);

  const openEntry = async (entry: Entry) => {
    const remotePath = joinPath(path, entry.name);
    if (entry.type === "directory") { setPath(remotePath); setSelected(null); return; }
    if (!credentials) return setNotice("Credentials are required");
    try { setSelected(entry); setContent(await read.mutateAsync({ credentials, path: remotePath })); setNotice("File loaded"); } catch (error) { setNotice(`ERROR: ${error instanceof Error ? error.message : "File read failed"}`); }
  };
  const goUp = () => setPath(path === "/" ? "/" : path.split("/").slice(0, -1).join("/") || "/");
  const deleteSelected = async () => { if (!selected || !credentials) return; Alert.alert("Delete item?", `This permanently deletes ${selected.name}.`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void (async () => { try { await remove.mutateAsync({ credentials, path: joinPath(path, selected.name) }); setSelected(null); setContent(""); setNotice("Deleted successfully"); await refresh(); } catch (error) { setNotice(`Unable to delete: ${error instanceof Error ? error.message : "permission denied"}`); } })() }]); };
  const saveSelected = async () => { if (!selected || !credentials) return; const saveNow = async (backup: boolean) => { try { if (backup) await write.mutateAsync({ credentials, path: `${joinPath(path, selected.name)}.bak`, content }); await write.mutateAsync({ credentials, path: joinPath(path, selected.name), content }); setNotice("File saved successfully"); } catch (error) { setNotice(`Unable to save: ${error instanceof Error ? error.message : "check permissions or connection"}`); } }; Alert.alert("Save file", "Choose whether to create a backup before saving.", [{ text: "Cancel", style: "cancel" }, { text: "Save without backup", onPress: () => void saveNow(false) }, { text: "Backup then save", onPress: () => void saveNow(true) }]); };
  const createFolder = async () => { if (!credentials) return; const name = `new-folder-${Date.now()}`; try { await mkdir.mutateAsync({ credentials, path: joinPath(path, name) }); setNotice("Folder created"); await refresh(); } catch (error) { setNotice(`ERROR: ${error instanceof Error ? error.message : "Create folder failed"}`); } };
  const downloadSelected = async () => { if (!selected || !credentials) return; const localUri = `${FileSystem.cacheDirectory ?? ""}${selected.name}`; try { await downloadRemoteFile(credentials, joinPath(path, selected.name), localUri, setTransfer); setNotice(`Downloaded to ${localUri}`); } catch (error) { setNotice(`PAUSED: ${error instanceof Error ? error.message : "Download interrupted"}`); } };
  const uploadFile = async () => { if (!credentials) return; const result = await DocumentPicker.getDocumentAsync({ type: "*/*", copyToCacheDirectory: true }); if (result.canceled) return; const asset = result.assets[0]; try { await uploadLocalFile(credentials, asset.uri, joinPath(path, asset.name), setTransfer); setNotice("Upload completed"); await refresh(); } catch (error) { setNotice(`Transfer paused: ${error instanceof Error ? error.message : "Upload interrupted"}`); } };
  const runPython = async () => { if (!selected || !credentials || !selected.name.toLowerCase().endsWith(".py")) return; setNotice("Running Python file…"); try { const command = `cd ${path.replace(/'/g, "'\\''")} && PYTHON=$(find . -maxdepth 3 -type f \( -path '*/.venv/bin/python' -o -path '*/venv/bin/python' \) -print -quit); if [ -n \"$PYTHON\" ]; then \"$PYTHON\" '${selected.name.replace(/'/g, "'\\''")}'; else python3 '${selected.name.replace(/'/g, "'\\''")}'; fi`; const result = await exec.mutateAsync({ credentials, command }); setNotice(result.stderr ? `Python completed with warnings: ${result.stderr.slice(0, 120)}` : "Python execution completed"); Alert.alert("Python output", `${result.stdout}${result.stderr ? `\\n\\n${result.stderr}` : ""}`.trim() || "No output"); } catch (error) { setNotice(`Python execution failed: ${error instanceof Error ? error.message : "interpreter unavailable"}`); } };

  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Text style={[styles.kicker, { color: colors.muted }]}>REMOTE STORAGE</Text><Text style={[styles.title, { color: colors.foreground }]}>Files</Text></View><View style={styles.headerActions}><Pressable onPress={() => void uploadFile()} style={({ pressed }) => [styles.upload, { borderColor: colors.primary, opacity: pressed ? .75 : 1 }]}><Text style={{ color: colors.primary, fontSize: 11, fontWeight: "800" }}>UPLOAD</Text></Pressable><Pressable onPress={() => void createFolder()} style={({ pressed }) => [styles.add, { backgroundColor: colors.primary, opacity: pressed ? .75 : 1 }]}><Text style={{ fontSize: 22, color: colors.background, lineHeight: 22 }}>+</Text></Pressable></View></View>
    <View style={[styles.pathBar, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="paperplane.fill" size={16} color={colors.primary} /><Pressable onPress={goUp} style={styles.flex}><Text style={[styles.path, { color: colors.foreground }]} numberOfLines={1}>⌂  {path}</Text></Pressable><Pressable onPress={() => void refresh()}><Text style={{ color: colors.primary, fontSize: 11, fontWeight: "800" }}>REFRESH</Text></Pressable></View>
    <View style={styles.toolbar}><Text style={[styles.sub, { color: notice.startsWith("ERROR") ? colors.error : colors.muted }]}>{notice}</Text><Pressable onPress={() => setShowCredentials((value) => !value)}><Text style={{ color: colors.primary, fontSize: 11, fontWeight: "800" }}>{showCredentials ? "HIDE AUTH" : "AUTH"}</Text></Pressable></View>
    {showCredentials && <View style={[styles.auth, { backgroundColor: colors.surface, borderColor: colors.border }]}><TextInput value={activeServer?.authMethod === "ssh-key" ? privateKey : password} onChangeText={activeServer?.authMethod === "ssh-key" ? setPrivateKey : setPassword} secureTextEntry={activeServer?.authMethod !== "ssh-key"} multiline={activeServer?.authMethod === "ssh-key"} placeholder={activeServer?.authMethod === "ssh-key" ? "Private key" : "Password"} placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><Text style={[styles.sub, { color: colors.muted }]}>Password-first connection. Host fingerprint verification is not required.</Text>{activeServer?.forceKeyboardInteractive && <TextInput value={otpCode} onChangeText={setOtpCode} placeholder="2FA / OTP code" placeholderTextColor={colors.muted} keyboardType="number-pad" style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} />}{activeServer?.jumpHost?.enabled && <TextInput value={activeServer.authMethod === "ssh-key" ? jumpPrivateKey : jumpPassword} onChangeText={activeServer.authMethod === "ssh-key" ? setJumpPrivateKey : setJumpPassword} secureTextEntry={activeServer.authMethod !== "ssh-key"} multiline={activeServer.authMethod === "ssh-key"} placeholder={`Jump host (${activeServer.jumpHost.host}) ${activeServer.authMethod === "ssh-key" ? "private key" : "password"}`} placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} />}<Text style={[styles.sub, { color: colors.muted }]}>Credentials are memory-only and never saved in the server profile.</Text></View>}
    <View style={[styles.list, { backgroundColor: colors.surface, borderColor: colors.border }]}>{entries.length === 0 ? <View style={styles.empty}><IconSymbol name="folder.fill" size={25} color={colors.muted} /><Text style={[styles.fileName, { color: colors.foreground }]}>No files found</Text><Text style={[styles.sub, { color: colors.muted }]}>This directory is empty or unavailable.</Text></View> : entries.slice().sort((a, b) => Number(b.type === "directory") - Number(a.type === "directory") || a.name.localeCompare(b.name)).map((entry, index) => <Pressable key={entry.name} onPress={() => void openEntry(entry)} style={({ pressed }) => [styles.entry, index < entries.length - 1 && { borderBottomWidth: 1, borderBottomColor: colors.border }, { opacity: pressed ? .65 : 1 }]}><View style={[styles.fileIcon, { backgroundColor: `${entry.type === "directory" ? "#4DA3FF" : "#B58CFF"}18` }]}><IconSymbol name={entry.type === "directory" ? "paperplane.fill" : "chevron.left.forwardslash.chevron.right"} size={18} color={entry.type === "directory" ? "#4DA3FF" : "#B58CFF"} /></View><View style={styles.flex}><Text style={[styles.fileName, { color: colors.foreground }]}>{entry.name}</Text><Text style={[styles.sub, { color: colors.muted }]}>{entry.permissions ?? (entry.type === "directory" ? "d---------" : "----------")} · {entry.size} bytes · {new Date(entry.modifiedAt).toLocaleString()}</Text></View><Text style={[styles.size, { color: colors.muted }]}>›</Text></Pressable>)}</View>
    {transfer && <View style={[styles.transfer, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.transferHeader}><Text style={[styles.fileName, { color: colors.foreground }]}>{transfer.direction === "download" ? "Downloading" : "Uploading"}</Text><Text style={[styles.sub, { color: colors.muted }]}>{transfer.status.toUpperCase()}</Text></View><View style={[styles.progressTrack, { backgroundColor: colors.border }]}><View style={[styles.progressFill, { width: `${Math.min(100, (transfer.completedBytes / Math.max(1, transfer.totalBytes)) * 100)}%`, backgroundColor: transfer.status === "completed" ? colors.success : colors.primary }]} /></View><Text style={[styles.sub, { color: colors.muted }]}>{Math.round((transfer.completedBytes / Math.max(1, transfer.totalBytes)) * 100)}% · {Math.round(transfer.speedBytesPerSecond / 1024)} KB/s · {transfer.etaSeconds}s remaining</Text></View>}
    {selected && <View style={[styles.preview, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.previewHeader}><View><Text style={[styles.kicker, { color: colors.muted }]}>SELECTED FILE</Text><Text style={[styles.previewTitle, { color: colors.foreground }]}>{selected.name}</Text></View><Pressable onPress={() => setSelected(null)}><Text style={{ color: colors.primary, fontWeight: "800", fontSize: 12 }}>CLOSE</Text></Pressable></View><TextInput value={content} onChangeText={setContent} multiline style={[styles.code, { color: colors.foreground }]} /><View style={styles.previewActions}><Pressable onPress={() => void downloadSelected()} style={[styles.smallAction, { backgroundColor: `${colors.primary}18` }]}><Text style={{ color: colors.primary, fontWeight: "800", fontSize: 11 }}>DOWNLOAD</Text></Pressable>{selected.name.toLowerCase().endsWith(".py") && <Pressable onPress={() => void runPython()} style={[styles.smallAction, { backgroundColor: `${colors.warning}18` }]}><Text style={{ color: colors.warning, fontWeight: "800", fontSize: 11 }}>RUN PYTHON</Text></Pressable>}<Pressable onPress={() => void saveSelected()} style={[styles.smallAction, { backgroundColor: `${colors.success}18` }]}><Text style={{ color: colors.success, fontWeight: "800", fontSize: 11 }}>SAVE</Text></Pressable><Pressable onPress={() => void deleteSelected()} style={[styles.smallAction, { backgroundColor: `${colors.error}18` }]}><Text style={{ color: colors.error, fontWeight: "800", fontSize: 11 }}>DELETE</Text></Pressable></View></View>}
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({   content: { paddingTop: 12, paddingBottom: 32 }, empty: { minHeight: 150, alignItems: "center", justifyContent: "center", padding: 20 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }, headerActions: { flexDirection: "row", alignItems: "center", gap: 8 }, upload: { height: 40, borderRadius: 13, borderWidth: 1, paddingHorizontal: 10, alignItems: "center", justifyContent: "center" }, kicker: { fontSize: 11, fontWeight: "800", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "800", marginTop: 6 }, add: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center" }, pathBar: { minHeight: 46, borderWidth: 1, borderRadius: 15, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 13 }, path: { flex: 1, fontSize: 12, fontFamily: "monospace" }, toolbar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 14 }, auth: { borderRadius: 15, borderWidth: 1, padding: 12, gap: 8, marginBottom: 12 }, input: { minHeight: 42, borderWidth: 1, borderRadius: 11, paddingHorizontal: 12, paddingVertical: 10, fontSize: 12 }, list: { borderRadius: 18, borderWidth: 1, paddingHorizontal: 14 }, entry: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: 11 }, fileIcon: { width: 34, height: 34, borderRadius: 11, alignItems: "center", justifyContent: "center" }, flex: { flex: 1 }, fileName: { fontSize: 13, fontWeight: "700" }, sub: { fontSize: 10, marginTop: 4 }, size: { fontSize: 18 }, transfer: { borderRadius: 15, borderWidth: 1, marginTop: 12, padding: 12, gap: 8 }, transferHeader: { flexDirection: "row", justifyContent: "space-between" }, progressTrack: { height: 8, borderRadius: 4, overflow: "hidden" }, progressFill: { height: "100%", borderRadius: 4 }, preview: { borderRadius: 18, borderWidth: 1, marginTop: 15, padding: 15 }, previewHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, previewTitle: { fontSize: 17, fontWeight: "800", marginTop: 4 }, code: { backgroundColor: "#0B0F13", borderRadius: 12, padding: 14, fontFamily: "monospace", fontSize: 11, lineHeight: 18, marginTop: 14, minHeight: 180, textAlignVertical: "top" }, previewActions: { flexDirection: "row", gap: 9, marginTop: 12 }, smallAction: { flex: 1, alignItems: "center", paddingVertical: 11, borderRadius: 11 }, verifyButton: { alignItems: "center", borderWidth: 1, borderRadius: 10, paddingVertical: 10 } });
