import { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useServer } from "@/lib/server-context";
import { errorMessage, formatBytes } from "@/lib/server-agent";

export default function HomeScreen() {
  const colors = useColors("dark"); const router = useRouter();
  const { profile, configured, health, refreshHealth } = useServer();
  const [refreshing, setRefreshing] = useState(false); const [notice, setNotice] = useState("Connect your server agent in Settings");
  const refresh = useCallback(async () => { if (!configured) { setNotice("Open Settings and add the agent HTTPS URL and token"); return; } setRefreshing(true); try { await refreshHealth(); setNotice("Live metrics updated"); } catch (error) { setNotice(errorMessage(error)); } finally { setRefreshing(false); } }, [configured, refreshHealth]);
  useEffect(() => { if (configured && !health) refresh(); }, [configured, health, refresh]);
  const online = Boolean(health);
  const metrics = useMemo(() => [
    { label: "CPU Usage", value: health ? `${health.cpu.usagePercent.toFixed(1)}%` : "—", detail: health ? `${health.cpu.cores} cores · live` : "Not connected", color: "#4DA3FF", icon: "chevron.left.forwardslash.chevron.right" as const },
    { label: "Memory", value: health ? `${formatBytes(health.memory.usedBytes)} / ${formatBytes(health.memory.totalBytes)}` : "—", detail: health ? `${health.memory.usagePercent.toFixed(1)}% allocated` : "Not connected", color: "#B58CFF", icon: "paperplane.fill" as const },
    { label: "Storage", value: health ? formatBytes(health.storage.totalBytes) : "—", detail: health ? `${health.storage.usagePercent.toFixed(1)}% used` : "Not connected", color: "#46D8E7", icon: "paperplane.fill" as const },
  ], [health]);
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.primary} />} contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.muted }]}>SERVER IDE / OVERVIEW</Text><Text style={[styles.title, { color: colors.foreground }]}>Good morning.</Text></View><View style={[styles.statusButton, { borderColor: online ? "#35D07F55" : "#FF5C7055" }]}><View style={[styles.dot, { backgroundColor: online ? "#35D07F" : "#FF5C70" }]} /><Text style={[styles.statusText, { color: online ? "#35D07F" : "#FF5C70" }]}>{online ? "ONLINE" : "OFFLINE"}</Text></View></View>
    <Pressable onPress={() => router.push("/settings")} style={({ pressed }) => [styles.serverCard, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.72 : 1 }]}><View style={styles.serverTop}><View style={[styles.serverIcon, { backgroundColor: "#4DA3FF18" }]}><IconSymbol name="paperplane.fill" size={22} color="#4DA3FF" /></View><View style={styles.flex}><Text style={[styles.cardLabel, { color: colors.muted }]}>ACTIVE SERVER</Text><Text style={[styles.serverName, { color: colors.foreground }]}>{profile.name}</Text><Text style={[styles.serverMeta, { color: colors.muted }]}>{health?.hostname || profile.baseUrl || "Configure agent connection"}</Text></View><IconSymbol name="chevron.right" size={20} color={colors.muted} /></View><View style={[styles.divider, { backgroundColor: colors.border }]} /><View style={styles.serverStats}><View><Text style={[styles.statValue, { color: colors.foreground }]}>{health?.latencyMs ?? "—"}{health ? " ms" : ""}</Text><Text style={[styles.statCaption, { color: colors.muted }]}>LATENCY</Text></View><View><Text style={[styles.statValue, { color: online ? "#35D07F" : "#FF5C70" }]}>{online ? "Ready" : "Offline"}</Text><Text style={[styles.statCaption, { color: colors.muted }]}>STATUS</Text></View><View><Text style={[styles.statValue, { color: colors.foreground }]}>{health ? "Live" : "—"}</Text><Text style={[styles.statCaption, { color: colors.muted }]}>UPDATED</Text></View></View></Pressable>
    <View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>System health</Text><Text style={[styles.sectionLink, { color: colors.primary }]} onPress={refresh}>Refresh</Text></View><View style={styles.metricGrid}>{metrics.map((metric) => <View key={metric.label} style={[styles.metricCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.metricIcon, { backgroundColor: `${metric.color}18` }]}><IconSymbol name={metric.icon} size={18} color={metric.color} /></View><Text style={[styles.metricLabel, { color: colors.muted }]}>{metric.label}</Text><Text style={[styles.metricValue, { color: colors.foreground }]} numberOfLines={2}>{metric.value}</Text><Text style={[styles.metricDetail, { color: metric.color }]}>{metric.detail}</Text></View>)}</View>
    <View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Quick actions</Text></View><View style={styles.actionRow}><Pressable onPress={() => router.push("/ssh")} style={({ pressed }) => [styles.action, { backgroundColor: "#4DA3FF", opacity: pressed ? 0.8 : 1 }]}><IconSymbol name="chevron.left.forwardslash.chevron.right" size={19} color="#07111B" /><Text style={styles.actionText}>Open terminal</Text></Pressable><Pressable onPress={() => router.push("/network")} style={({ pressed }) => [styles.action, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.7 : 1 }]}><IconSymbol name="paperplane.fill" size={19} color="#46D8E7" /><Text style={[styles.actionText, { color: colors.foreground }]}>Network</Text></Pressable></View>
    <View style={[styles.notice, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.noticeIcon, { backgroundColor: online ? "#35D07F18" : "#FFB54718" }]}><IconSymbol name="chevron.left.forwardslash.chevron.right" size={17} color={online ? "#35D07F" : "#FFB547"} /></View><View style={styles.flex}><Text style={[styles.noticeTitle, { color: colors.foreground }]}>{online ? "Live agent connected" : "Agent connection required"}</Text><Text style={[styles.noticeText, { color: colors.muted }]}>{notice}</Text></View></View>
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 32 }, header: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 24 }, eyebrow: { fontSize: 11, fontWeight: "700", letterSpacing: 1.4, marginBottom: 7 }, title: { fontSize: 30, fontWeight: "800", letterSpacing: -0.8 }, statusButton: { flexDirection: "row", alignItems: "center", gap: 7, borderWidth: 1, borderRadius: 20, paddingHorizontal: 11, paddingVertical: 8 }, dot: { width: 7, height: 7, borderRadius: 4 }, statusText: { fontSize: 10, fontWeight: "800", letterSpacing: 0.8 }, serverCard: { borderRadius: 22, borderWidth: 1, padding: 16, marginBottom: 25 }, serverTop: { flexDirection: "row", alignItems: "center", gap: 12 }, serverIcon: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center" }, flex: { flex: 1 }, cardLabel: { fontSize: 10, fontWeight: "700", letterSpacing: 1.1 }, serverName: { fontSize: 19, fontWeight: "800", marginTop: 2 }, serverMeta: { fontSize: 11, marginTop: 3 }, divider: { height: 1, marginVertical: 15 }, serverStats: { flexDirection: "row", justifyContent: "space-between" }, statValue: { fontSize: 15, fontWeight: "800" }, statCaption: { fontSize: 9, fontWeight: "700", letterSpacing: 0.7, marginTop: 4 }, sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 11, marginTop: 2 }, sectionTitle: { fontSize: 17, fontWeight: "800" }, sectionLink: { fontSize: 12, fontWeight: "700" }, metricGrid: { flexDirection: "row", gap: 9, marginBottom: 24 }, metricCard: { flex: 1, minHeight: 148, borderRadius: 17, borderWidth: 1, padding: 12 }, metricIcon: { width: 32, height: 32, borderRadius: 10, alignItems: "center", justifyContent: "center", marginBottom: 13 }, metricLabel: { fontSize: 10, fontWeight: "600" }, metricValue: { fontSize: 15, fontWeight: "800", marginTop: 5 }, metricDetail: { fontSize: 10, marginTop: 6, fontWeight: "600" }, actionRow: { flexDirection: "row", gap: 10, marginBottom: 24 }, action: { flex: 1, minHeight: 49, borderRadius: 15, borderWidth: 1, borderColor: "transparent", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, actionText: { color: "#07111B", fontSize: 13, fontWeight: "800" }, notice: { borderRadius: 18, borderWidth: 1, minHeight: 74, padding: 14, flexDirection: "row", alignItems: "center", gap: 12 }, noticeIcon: { width: 36, height: 36, borderRadius: 11, alignItems: "center", justifyContent: "center" }, noticeTitle: { fontSize: 13, fontWeight: "800" }, noticeText: { fontSize: 10, lineHeight: 15, marginTop: 4 } });
