import { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useServer } from "@/lib/server-context";
import { errorMessage, formatBytes, serverAgent, type NetworkSnapshot } from "@/lib/server-agent";

export default function NetworkScreen() {
  const colors = useColors("dark"); const { profile, configured } = useServer(); const [snapshots, setSnapshots] = useState<NetworkSnapshot[]>([]); const [notice, setNotice] = useState("Connect the server agent for live traffic"); const [polling, setPolling] = useState(true);
  const refresh = useCallback(async () => { if (!configured) return; try { const next = await serverAgent.network(profile); setSnapshots((old) => [...old.slice(-23), next]); setNotice(`Live sample · ${new Date(next.sampledAt).toLocaleTimeString()}`); } catch (error) { setNotice(errorMessage(error)); } }, [configured, profile]);
  useEffect(() => { refresh(); }, [refresh]);
  useEffect(() => { if (!polling || !configured) return; const timer = setInterval(refresh, 5000); return () => clearInterval(timer); }, [polling, configured, refresh]);
  const current = snapshots.at(-1); const deltas = useMemo(() => snapshots.slice(1).map((item, index) => ({ rx: Math.max(0, item.rxBytes - snapshots[index].rxBytes), tx: Math.max(0, item.txBytes - snapshots[index].txBytes) })), [snapshots]); const max = Math.max(1, ...deltas.flatMap((item) => [item.rx, item.tx]));
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={[styles.kicker, { color: colors.muted }]}>NETWORK / TELEMETRY</Text><Text style={[styles.title, { color: colors.foreground }]}>Traffic</Text></View><View style={[styles.pill, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.blueDot} /><Text style={[styles.pillText, { color: colors.foreground }]}>{current?.interface || "—"}</Text></View></View>
    <View style={[styles.live, { backgroundColor: current ? "#35D07F12" : "#FFB54712", borderColor: current ? "#35D07F44" : "#FFB54744" }]}><IconSymbol name="paperplane.fill" size={18} color={current ? "#35D07F" : "#FFB547"} /><View style={styles.flex}><Text style={[styles.liveTitle, { color: colors.foreground }]}>{current ? "Live agent data" : "Connection required"}</Text><Text style={[styles.liveText, { color: colors.muted }]}>{notice}</Text></View></View>
    <View style={[styles.totalCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardHeader}><Text style={[styles.cardTitle, { color: colors.foreground }]}>Total traffic</Text><Text style={[styles.sub, { color: colors.muted }]}>{current?.interface || "No interface"}</Text></View><View style={styles.trafficRow}><View><View style={styles.labelRow}><View style={[styles.miniDot, { backgroundColor: "#35D07F" }]} /><Text style={[styles.sub, { color: colors.muted }]}>Download (RX)</Text></View><Text style={[styles.bigValue, { color: colors.foreground }]}>{current ? formatBytes(current.rxBytes) : "—"}</Text></View><View><View style={styles.labelRow}><View style={[styles.miniDot, { backgroundColor: "#4DA3FF" }]} /><Text style={[styles.sub, { color: colors.muted }]}>Upload (TX)</Text></View><Text style={[styles.bigValue, { color: colors.foreground }]}>{current ? formatBytes(current.txBytes) : "—"}</Text></View></View></View>
    <View style={[styles.segment, { backgroundColor: colors.surface }]}><Pressable onPress={() => setPolling(!polling)} style={[styles.segmentItem, { backgroundColor: polling ? "#E9EDF2" : "transparent" }]}><Text style={[styles.segmentText, { color: polling ? "#11161C" : colors.muted }]}>{polling ? "LIVE 5s" : "PAUSED"}</Text></Pressable><Pressable onPress={refresh} style={styles.segmentItem}><Text style={[styles.segmentText, { color: colors.primary }]}>REFRESH NOW</Text></Pressable></View>
    <View style={[styles.chartCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardHeader}><Text style={[styles.cardTitle, { color: colors.foreground }]}>Traffic chart</Text><Text style={[styles.sub, { color: colors.muted }]}>Last {Math.max(deltas.length, 1)} samples</Text></View><View style={styles.chart}><View style={styles.gridLine} /><View style={[styles.gridLine, { top: 50 }]} /><View style={[styles.gridLine, { top: 100 }]} /><View style={styles.bars}>{(deltas.length ? deltas : [{ rx: 0, tx: 0 }]).map((item, index) => <View key={index} style={styles.barGroup}><View style={[styles.bar, { height: Math.max(4, item.rx / max * 120), backgroundColor: "#35D07F" }]} /><View style={[styles.bar, { height: Math.max(4, item.tx / max * 120), backgroundColor: "#4DA3FF" }]} /></View>)}</View></View><View style={styles.axis}><Text style={styles.axisText}>OLDER</Text><Text style={styles.axisText}>NOW</Text></View></View>
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 32 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 22 }, kicker: { fontSize: 11, fontWeight: "800", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "800", marginTop: 6 }, pill: { flexDirection: "row", alignItems: "center", gap: 7, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 18, borderWidth: 1 }, blueDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#4DA3FF" }, pillText: { fontSize: 12, fontWeight: "800" }, live: { borderRadius: 16, borderWidth: 1, padding: 14, flexDirection: "row", gap: 11, marginBottom: 15 }, flex: { flex: 1 }, liveTitle: { fontWeight: "800", fontSize: 13, marginBottom: 5 }, liveText: { fontSize: 11, lineHeight: 16 }, totalCard: { borderRadius: 20, borderWidth: 1, padding: 16, marginBottom: 14 }, cardHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 18 }, cardTitle: { fontWeight: "800", fontSize: 15 }, sub: { fontSize: 10, lineHeight: 15 }, trafficRow: { flexDirection: "row", justifyContent: "space-between" }, labelRow: { flexDirection: "row", alignItems: "center", gap: 6 }, miniDot: { width: 6, height: 6, borderRadius: 3 }, bigValue: { fontSize: 19, fontWeight: "800", marginTop: 6 }, segment: { flexDirection: "row", borderRadius: 13, padding: 4, marginBottom: 14 }, segmentItem: { flex: 1, borderRadius: 10, alignItems: "center", paddingVertical: 9 }, segmentText: { fontSize: 10, fontWeight: "800" }, chartCard: { borderRadius: 20, borderWidth: 1, padding: 16 }, chart: { height: 150, position: "relative", justifyContent: "flex-end" }, gridLine: { position: "absolute", left: 0, right: 0, top: 0, borderTopWidth: 1, borderTopColor: "#33404D55" }, bars: { height: 130, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-around" }, barGroup: { flexDirection: "row", alignItems: "flex-end", gap: 3 }, bar: { width: 8, borderRadius: 3 }, axis: { flexDirection: "row", justifyContent: "space-between", marginTop: 10 }, axisText: { color: "#697583", fontSize: 9 } });
