import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";

const ranges = ["5 Min", "Hour", "Day", "Month", "Year"];
const bars = [42, 68, 54, 82, 61, 93, 77, 88, 58, 74, 96, 69];
export default function NetworkScreen() {
  const colors = useColors("dark"); const [range, setRange] = useState("Hour"); const [iface, setIface] = useState("eth0"); const [pinging, setPinging] = useState(true);
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={[styles.kicker, { color: colors.muted }]}>NETWORK / TELEMETRY</Text><Text style={[styles.title, { color: colors.foreground }]}>Traffic</Text></View><Pressable onPress={() => setIface(iface === "eth0" ? "wlan0" : "eth0")} style={({ pressed }) => [styles.pill, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.7 : 1 }]}><View style={styles.blueDot} /><Text style={[styles.pillText, { color: colors.foreground }]}>{iface}</Text><IconSymbol name="chevron.right" size={14} color={colors.muted} /></Pressable></View>
    <View style={[styles.demo, { backgroundColor: "#FFB54712", borderColor: "#FFB54744" }]}><IconSymbol name="paperplane.fill" size={18} color="#FFB547" /><View style={styles.flex}><Text style={[styles.demoTitle, { color: colors.foreground }]}>Demo mode</Text><Text style={[styles.demoText, { color: colors.muted }]}>Install the agent on your server to view real-time traffic data.</Text></View></View>
    <View style={[styles.totalCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardHeader}><Text style={[styles.cardTitle, { color: colors.foreground }]}>Total traffic</Text><Text style={[styles.sub, { color: colors.muted }]}>{iface}</Text></View><View style={styles.trafficRow}><View><View style={styles.labelRow}><View style={[styles.miniDot, { backgroundColor: "#35D07F" }]} /><Text style={[styles.sub, { color: colors.muted }]}>Download (RX)</Text></View><Text style={[styles.bigValue, { color: colors.foreground }]}>560.68 MB</Text></View><View><View style={styles.labelRow}><View style={[styles.miniDot, { backgroundColor: "#4DA3FF" }]} /><Text style={[styles.sub, { color: colors.muted }]}>Upload (TX)</Text></View><Text style={[styles.bigValue, { color: colors.foreground }]}>259.44 MB</Text></View></View><View style={[styles.dateRow, { borderTopColor: colors.border }]}><Text style={[styles.sub, { color: colors.muted }]}>Created\n2026/08/30</Text><Text style={[styles.sub, { color: colors.muted }]}>Updated\n2026/08/30 5:55</Text></View></View>
    <View style={[styles.segment, { backgroundColor: colors.surface }]}>{ranges.map((item) => <Pressable key={item} onPress={() => setRange(item)} style={[styles.segmentItem, range === item && { backgroundColor: "#E9EDF2" }]}><Text style={[styles.segmentText, { color: range === item ? "#11161C" : colors.muted }]}>{item}</Text></Pressable>)}</View>
    <View style={[styles.chartCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardHeader}><Text style={[styles.cardTitle, { color: colors.foreground }]}>Traffic chart</Text><Text style={[styles.sub, { color: colors.muted }]}>{range}</Text></View><View style={styles.chart}><View style={styles.gridLine} /><View style={[styles.gridLine, { top: 36 }]} /><View style={[styles.gridLine, { top: 72 }]} /><View style={styles.bars}>{bars.map((height, index) => <View key={index} style={styles.barGroup}><View style={[styles.bar, { height: height * 0.62, backgroundColor: "#35D07F" }]} /><View style={[styles.bar, { height: height * 0.42, backgroundColor: "#4DA3FF" }]} /></View>)}</View></View><View style={styles.axis}><Text style={styles.axisText}>00:00</Text><Text style={styles.axisText}>12:00</Text><Text style={styles.axisText}>24:00</Text></View></View><View style={[styles.pingCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardHeader}><View><Text style={[styles.cardTitle, { color: colors.foreground }]}>TCP Ping</Text><Text style={[styles.sub, { color: colors.muted }]}>memo · port 22</Text></View><Pressable onPress={() => setPinging(!pinging)} style={[styles.pingStatus, { backgroundColor: pinging ? "#35D07F18" : "#FF5C7018" }]}><View style={[styles.miniDot, { backgroundColor: pinging ? "#35D07F" : "#FF5C70" }]} /><Text style={{ color: pinging ? "#35D07F" : "#FF5C70", fontSize: 10, fontWeight: "800" }}>{pinging ? "Connected" : "Failed"}</Text></Pressable></View><View style={styles.pingStats}><View><Text style={[styles.pingValue, { color: pinging ? "#FF5C70" : colors.muted }]}>{pinging ? "42" : "—"}<Text style={{ fontSize: 12 }}> ms</Text></Text><Text style={[styles.sub, { color: colors.muted }]}>CURRENT LATENCY</Text></View><View><Text style={[styles.pingValue, { color: colors.foreground }]}>0.0%</Text><Text style={[styles.sub, { color: colors.muted }]}>PACKET LOSS</Text></View><Pressable onPress={() => setPinging(!pinging)} style={[styles.pingButton, { backgroundColor: pinging ? "#FF5C7018" : "#35D07F18" }]}><Text style={{ color: pinging ? "#FF5C70" : "#35D07F", fontWeight: "800", fontSize: 11 }}>{pinging ? "STOP" : "START"}</Text></Pressable></View></View>
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 32 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 22 }, kicker: { fontSize: 11, fontWeight: "800", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "800", marginTop: 6 }, pill: { flexDirection: "row", alignItems: "center", gap: 7, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 18, borderWidth: 1 }, blueDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#4DA3FF" }, pillText: { fontSize: 12, fontWeight: "800" }, demo: { borderRadius: 16, borderWidth: 1, padding: 14, flexDirection: "row", gap: 11, marginBottom: 15 }, flex: { flex: 1 }, demoTitle: { fontWeight: "800", fontSize: 13, marginBottom: 5 }, demoText: { fontSize: 11, lineHeight: 16 }, totalCard: { borderRadius: 20, borderWidth: 1, padding: 16, marginBottom: 14 }, cardHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 18 }, cardTitle: { fontWeight: "800", fontSize: 15 }, sub: { fontSize: 10, lineHeight: 15 }, trafficRow: { flexDirection: "row", justifyContent: "space-between" }, labelRow: { flexDirection: "row", alignItems: "center", gap: 6 }, miniDot: { width: 6, height: 6, borderRadius: 3 }, bigValue: { fontSize: 20, fontWeight: "800", marginTop: 6 }, dateRow: { flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, marginTop: 16, paddingTop: 12 }, segment: { flexDirection: "row", borderRadius: 13, padding: 4, marginBottom: 14 }, segmentItem: { flex: 1, borderRadius: 10, alignItems: "center", paddingVertical: 8 }, segmentText: { fontSize: 10, fontWeight: "800" }, chartCard: { borderRadius: 20, borderWidth: 1, padding: 16 }, chart: { height: 150, position: "relative", justifyContent: "flex-end" }, gridLine: { position: "absolute", left: 0, right: 0, top: 0, borderTopWidth: 1, borderTopColor: "#33404D55" }, bars: { height: 130, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-around" }, barGroup: { flexDirection: "row", alignItems: "flex-end", gap: 2 }, bar: { width: 7, borderRadius: 3 }, axis: { flexDirection: "row", justifyContent: "space-between", marginTop: 10 }, axisText: { color: "#697583", fontSize: 9 }, pingCard: { borderRadius: 20, borderWidth: 1, padding: 16, marginTop: 14 }, pingStatus: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 9, paddingVertical: 7, borderRadius: 12 }, pingStats: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" }, pingValue: { fontSize: 24, fontWeight: "800" }, pingButton: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 11 } });
