import { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";

const initialProcesses = [
  { pid: "1", command: "systemd", user: "root", status: "Running", cpu: "0.1%", memory: "18 MB" },
  { pid: "482", command: "sshd: root@pts/0", user: "root", status: "Running", cpu: "0.4%", memory: "12 MB" },
  { pid: "1204", command: "node server.js", user: "deploy", status: "Idle", cpu: "2.8%", memory: "284 MB" },
  { pid: "1855", command: "postgres -D /data", user: "postgres", status: "Running", cpu: "1.2%", memory: "126 MB" },
];

export default function ProcessesScreen() {
  const colors = useColors("dark");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<(typeof initialProcesses)[number] | null>(null);
  const [processes, setProcesses] = useState(initialProcesses);
  const filtered = useMemo(() => processes.filter((p) => `${p.pid} ${p.command} ${p.user}`.toLowerCase().includes(query.toLowerCase())), [processes, query]);
  const kill = () => { if (!selected) return; setProcesses((items) => items.filter((item) => item.pid !== selected.pid)); setSelected(null); };
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={[styles.kicker, { color: colors.muted }]}>LIVE MONITOR</Text><Text style={[styles.title, { color: colors.foreground }]}>Processes</Text></View><View style={[styles.count, { backgroundColor: "#4DA3FF18" }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>{processes.length}</Text></View></View>
    <View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="paperplane.fill" size={17} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search PID, command, user" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground }]} /></View>
    <View style={styles.legend}><Text style={[styles.legendText, { color: colors.muted }]}>PROCESS ID</Text><Text style={[styles.legendText, { color: colors.muted }]}>RESOURCE</Text></View>
    {filtered.map((item) => <Pressable key={item.pid} onPress={() => setSelected(item)} style={({ pressed }) => [styles.row, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.68 : 1 }]}><View style={[styles.pid, { backgroundColor: item.status === "Idle" ? "#FFB54718" : "#35D07F18" }]}><Text style={{ color: item.status === "Idle" ? "#FFB547" : "#35D07F", fontWeight: "800", fontSize: 12 }}>{item.pid}</Text></View><View style={styles.flex}><Text style={[styles.command, { color: colors.foreground }]} numberOfLines={1}>{item.command}</Text><Text style={[styles.sub, { color: colors.muted }]}>{item.user} · {item.status}</Text></View><View style={styles.resource}><Text style={[styles.resourceValue, { color: colors.foreground }]}>{item.cpu}</Text><Text style={[styles.sub, { color: colors.muted }]}>{item.memory}</Text></View><IconSymbol name="chevron.right" size={18} color={colors.muted} /></Pressable>)}
    {filtered.length === 0 && <View style={styles.empty}><IconSymbol name="paperplane.fill" size={26} color={colors.muted} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>No processes found</Text><Text style={[styles.sub, { color: colors.muted }]}>Try another search phrase.</Text></View>}
  </ScrollView><Modal visible={!!selected} transparent animationType="slide" onRequestClose={() => setSelected(null)}><View style={styles.modalBackdrop}><View style={[styles.modal, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.modalHandle} /><Text style={[styles.kicker, { color: colors.muted }]}>PROCESS DETAIL</Text><Text style={[styles.modalTitle, { color: colors.foreground }]}>{selected?.command}</Text><View style={styles.detailGrid}>{[["Process ID", selected?.pid], ["User", selected?.user], ["Status", selected?.status], ["CPU Usage", selected?.cpu], ["Memory Usage", selected?.memory]].map(([label, value]) => <View key={label} style={[styles.detailRow, { borderBottomColor: colors.border }]}><Text style={[styles.sub, { color: colors.muted }]}>{label}</Text><Text style={[styles.detailValue, { color: label === "Status" && value === "Idle" ? "#FFB547" : colors.foreground }]}>{value}</Text></View>)}</View><Pressable onPress={kill} style={({ pressed }) => [styles.kill, { backgroundColor: "#FF5C7018", borderColor: "#FF5C7055", opacity: pressed ? 0.7 : 1 }]}><Text style={{ color: "#FF5C70", fontWeight: "800" }}>Stop process</Text></Pressable><Pressable onPress={() => setSelected(null)} style={styles.cancel}><Text style={[styles.sub, { color: colors.muted }]}>Cancel</Text></Pressable></View></View></Modal></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 32 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 22 }, kicker: { fontSize: 11, fontWeight: "800", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "800", marginTop: 6 }, count: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center" }, search: { height: 48, borderRadius: 15, borderWidth: 1, flexDirection: "row", alignItems: "center", paddingHorizontal: 14, gap: 10, marginBottom: 18 }, input: { flex: 1, fontSize: 13 }, legend: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 8, marginBottom: 8 }, legendText: { fontSize: 9, fontWeight: "800", letterSpacing: 1 }, row: { minHeight: 76, borderRadius: 17, borderWidth: 1, marginBottom: 9, padding: 13, flexDirection: "row", alignItems: "center", gap: 11 }, pid: { width: 42, height: 42, borderRadius: 13, alignItems: "center", justifyContent: "center" }, flex: { flex: 1 }, command: { fontWeight: "700", fontSize: 13 }, sub: { fontSize: 11, marginTop: 5 }, resource: { alignItems: "flex-end", marginRight: 2 }, resourceValue: { fontSize: 13, fontWeight: "800" }, empty: { alignItems: "center", paddingTop: 60 }, emptyTitle: { fontWeight: "800", fontSize: 16, marginTop: 13 }, modalBackdrop: { flex: 1, backgroundColor: "#000000AA", justifyContent: "flex-end" }, modal: { borderTopLeftRadius: 28, borderTopRightRadius: 28, borderWidth: 1, padding: 22, paddingBottom: 32 }, modalHandle: { alignSelf: "center", width: 40, height: 4, borderRadius: 2, backgroundColor: "#66707D", marginBottom: 24 }, modalTitle: { fontSize: 21, fontWeight: "800", marginTop: 7, marginBottom: 18 }, detailGrid: { marginBottom: 17 }, detailRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 12, borderBottomWidth: 1 }, detailValue: { fontSize: 13, fontWeight: "700" }, kill: { minHeight: 48, borderWidth: 1, borderRadius: 15, alignItems: "center", justifyContent: "center" }, cancel: { alignItems: "center", paddingTop: 17 } });
