import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Modal, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useServer } from "@/lib/server-context";
import { errorMessage, formatBytes, serverAgent, type ServerProcess } from "@/lib/server-agent";

export default function ProcessesScreen() {
  const colors = useColors("dark"); const { profile, configured } = useServer();
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<ServerProcess | null>(null); const [processes, setProcesses] = useState<ServerProcess[]>([]); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState("Pull to refresh live processes");
  const refresh = useCallback(async () => { if (!configured) { setNotice("Configure the server agent in Settings"); return; } setLoading(true); try { const result = await serverAgent.processes(profile); setProcesses(result.processes); setNotice(`${result.processes.length} live processes`); } catch (error) { setNotice(errorMessage(error)); } finally { setLoading(false); } }, [configured, profile]);
  useEffect(() => { refresh(); }, [refresh]);
  const filtered = useMemo(() => processes.filter((item) => `${item.pid} ${item.command} ${item.user}`.toLowerCase().includes(query.toLowerCase())), [processes, query]);
  const stop = () => { if (!selected) return; Alert.alert("Stop process", `Send SIGTERM to PID ${selected.pid}?`, [{ text: "Cancel", style: "cancel" }, { text: "Stop", style: "destructive", onPress: async () => { try { await serverAgent.stopProcess(profile, selected.pid); setSelected(null); await refresh(); } catch (error) { setNotice(errorMessage(error)); } } }]); };
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={refresh} tintColor={colors.primary} />} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={[styles.kicker, { color: colors.muted }]}>LIVE MONITOR</Text><Text style={[styles.title, { color: colors.foreground }]}>Processes</Text></View><View style={[styles.count, { backgroundColor: "#4DA3FF18" }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>{processes.length}</Text></View></View>
    <View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="paperplane.fill" size={17} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search PID, command, user" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground }]} /></View><Text style={[styles.notice, { color: colors.muted }]}>{notice}</Text>
    <View style={styles.legend}><Text style={[styles.legendText, { color: colors.muted }]}>PROCESS ID</Text><Text style={[styles.legendText, { color: colors.muted }]}>RESOURCE</Text></View>
    {filtered.map((item) => <Pressable key={item.pid} onPress={() => setSelected(item)} style={({ pressed }) => [styles.row, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.68 : 1 }]}><View style={[styles.pid, { backgroundColor: item.status.includes("Z") ? "#FFB54718" : "#35D07F18" }]}><Text style={{ color: item.status.includes("Z") ? "#FFB547" : "#35D07F", fontWeight: "800", fontSize: 12 }}>{item.pid}</Text></View><View style={styles.flex}><Text style={[styles.command, { color: colors.foreground }]} numberOfLines={1}>{item.command}</Text><Text style={[styles.sub, { color: colors.muted }]}>{item.user} · {item.status}</Text></View><View style={styles.resource}><Text style={[styles.resourceValue, { color: colors.foreground }]}>{item.cpuPercent.toFixed(1)}%</Text><Text style={[styles.sub, { color: colors.muted }]}>{formatBytes(item.memoryBytes)}</Text></View><IconSymbol name="chevron.right" size={18} color={colors.muted} /></Pressable>)}
    {!loading && filtered.length === 0 && <View style={styles.empty}><IconSymbol name="chevron.left.forwardslash.chevron.right" size={26} color={colors.muted} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>No live processes</Text><Text style={[styles.sub, { color: colors.muted }]}>{configured ? "Refresh or change the search." : "Configure the agent first."}</Text></View>}
  </ScrollView><Modal visible={!!selected} transparent animationType="slide" onRequestClose={() => setSelected(null)}><View style={styles.modalBackdrop}><View style={[styles.modal, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.modalHandle} /><Text style={[styles.kicker, { color: colors.muted }]}>PROCESS DETAIL</Text><Text style={[styles.modalTitle, { color: colors.foreground }]}>{selected?.command}</Text>{[["Process ID", selected?.pid], ["User", selected?.user], ["State", selected?.status], ["CPU Usage", `${selected?.cpuPercent ?? 0}%`], ["Memory", formatBytes(selected?.memoryBytes ?? 0)]].map(([label, value]) => <View key={String(label)} style={[styles.detailRow, { borderBottomColor: colors.border }]}><Text style={[styles.sub, { color: colors.muted }]}>{label}</Text><Text style={[styles.detailValue, { color: colors.foreground }]}>{value}</Text></View>)}<Pressable onPress={stop} style={[styles.kill, { borderColor: "#FF5C7055", backgroundColor: "#FF5C7018" }]}><Text style={{ color: "#FF5C70", fontWeight: "800" }}>Stop process</Text></Pressable><Pressable onPress={() => setSelected(null)} style={styles.cancel}><Text style={[styles.sub, { color: colors.muted }]}>Cancel</Text></Pressable></View></View></Modal></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 32 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 22 }, kicker: { fontSize: 11, fontWeight: "800", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "800", marginTop: 6 }, count: { minWidth: 36, height: 36, paddingHorizontal: 9, borderRadius: 12, alignItems: "center", justifyContent: "center" }, search: { height: 48, borderRadius: 15, borderWidth: 1, flexDirection: "row", alignItems: "center", paddingHorizontal: 14, gap: 10 }, input: { flex: 1, fontSize: 13 }, notice: { fontSize: 10, marginVertical: 10 }, legend: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 8, marginBottom: 8 }, legendText: { fontSize: 9, fontWeight: "800", letterSpacing: 1 }, row: { minHeight: 76, borderRadius: 17, borderWidth: 1, marginBottom: 9, padding: 13, flexDirection: "row", alignItems: "center", gap: 11 }, pid: { width: 46, height: 42, borderRadius: 13, alignItems: "center", justifyContent: "center" }, flex: { flex: 1 }, command: { fontWeight: "700", fontSize: 13 }, sub: { fontSize: 10, marginTop: 4 }, resource: { alignItems: "flex-end", marginRight: 2 }, resourceValue: { fontSize: 13, fontWeight: "800" }, empty: { alignItems: "center", paddingTop: 60 }, emptyTitle: { fontWeight: "800", fontSize: 16, marginTop: 13 }, modalBackdrop: { flex: 1, backgroundColor: "#000000AA", justifyContent: "flex-end" }, modal: { borderTopLeftRadius: 28, borderTopRightRadius: 28, borderWidth: 1, padding: 22, paddingBottom: 32 }, modalHandle: { alignSelf: "center", width: 40, height: 4, borderRadius: 2, backgroundColor: "#66707D", marginBottom: 24 }, modalTitle: { fontSize: 18, fontWeight: "800", marginTop: 7, marginBottom: 18 }, detailRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 11, borderBottomWidth: 1 }, detailValue: { fontSize: 12, fontWeight: "700", maxWidth: "62%" }, kill: { minHeight: 48, borderWidth: 1, borderRadius: 15, alignItems: "center", justifyContent: "center", marginTop: 18 }, cancel: { alignItems: "center", paddingTop: 14 } });
