import { useRef, useState } from "react";
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useServer } from "@/lib/server-context";
import { errorMessage, serverAgent } from "@/lib/server-agent";

type Line = { text: string; tone: "command" | "output" | "error" | "system" };
const stages = ["Network", "Auth", "Shell", "Ready"];
export default function SSHScreen() {
  const colors = useColors("dark"); const { profile, configured, health, refreshHealth } = useServer(); const scroll = useRef<ScrollView>(null);
  const [connected, setConnected] = useState(Boolean(health)); const [running, setRunning] = useState(false); const [command, setCommand] = useState(""); const [cwd, setCwd] = useState(""); const [lines, setLines] = useState<Line[]>([{ text: configured ? "Agent configured. Tap Connect to start a live command session." : "Configure the HTTPS agent in Settings first.", tone: "system" }]);
  const connect = async () => { if (!configured) { setLines((old) => [...old, { text: "Connection missing: open Settings and add the agent URL and token.", tone: "error" }]); return; } setRunning(true); try { const result = await refreshHealth(); setConnected(true); setLines((old) => [...old, { text: `Connected to ${result.hostname} over encrypted HTTPS.`, tone: "system" }]); } catch (error) { setConnected(false); setLines((old) => [...old, { text: errorMessage(error), tone: "error" }]); } finally { setRunning(false); } };
  const run = async () => { const value = command.trim(); if (!value || running) return; setCommand(""); setLines((old) => [...old, { text: `$ ${value}`, tone: "command" }]); setRunning(true); try { const result = await serverAgent.command(profile, value, cwd || undefined); setCwd(result.cwd); const additions: Line[] = []; if (result.stdout) additions.push({ text: result.stdout.trimEnd(), tone: "output" }); if (result.stderr) additions.push({ text: result.stderr.trimEnd(), tone: "error" }); additions.push({ text: `[exit ${result.exitCode}]`, tone: result.exitCode === 0 ? "system" : "error" }); setLines((old) => [...old, ...additions]); } catch (error) { setLines((old) => [...old, { text: errorMessage(error), tone: "error" }]); } finally { setRunning(false); setTimeout(() => scroll.current?.scrollToEnd({ animated: true }), 100); } };
  return <ScreenContainer className="px-5" containerClassName="bg-background"><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView ref={scroll} keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Text style={[styles.kicker, { color: colors.muted }]}>REMOTE WORKSPACE</Text><Text style={[styles.title, { color: colors.foreground }]}>SSH terminal</Text></View><View style={[styles.connection, { backgroundColor: connected ? "#35D07F18" : "#FF5C7018" }]}><View style={[styles.dot, { backgroundColor: connected ? "#35D07F" : "#FF5C70" }]} /><Text style={{ color: connected ? "#35D07F" : "#FF5C70", fontSize: 11, fontWeight: "800" }}>{connected ? "READY" : "CLOSED"}</Text></View></View>
    <View style={[styles.session, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.sessionTop}><View style={[styles.sessionIcon, { backgroundColor: "#4DA3FF18" }]}><IconSymbol name="chevron.left.forwardslash.chevron.right" size={19} color="#4DA3FF" /></View><View style={styles.flex}><Text style={[styles.sessionName, { color: colors.foreground }]}>{profile.name}</Text><Text style={[styles.sub, { color: colors.muted }]}>{health?.hostname || profile.baseUrl || "No server configured"}</Text></View><Text style={{ color: connected ? "#35D07F" : "#FF5C70", fontSize: 10, fontWeight: "700" }}>{connected ? "Connected" : "Disconnected"}</Text></View>
      {stages.map((stage, index) => <View key={stage} style={styles.stage}><View style={[styles.stageLine, { backgroundColor: index === stages.length - 1 ? "transparent" : connected ? "#35D07F" : colors.border }]} /><View style={[styles.stageIcon, { backgroundColor: connected ? "#35D07F" : colors.surface, borderColor: connected ? "#35D07F" : colors.border }]}><Text style={{ color: connected ? "#07111B" : colors.muted, fontSize: 10, fontWeight: "800" }}>{connected ? "✓" : "·"}</Text></View><View><Text style={[styles.stageTitle, { color: colors.foreground }]}>{stage}</Text><Text style={[styles.sub, { color: colors.muted }]}>{connected ? "Complete" : "Waiting"}</Text></View></View>)}
      <Pressable disabled={running} onPress={connected ? () => setConnected(false) : connect} style={({ pressed }) => [styles.close, { borderColor: connected ? "#FF5C7055" : "#35D07F55", opacity: pressed || running ? 0.65 : 1 }]}><Text style={{ color: connected ? "#FF5C70" : "#35D07F", fontWeight: "800" }}>{running ? "PLEASE WAIT…" : connected ? "Close session" : "Connect"}</Text></Pressable></View>
    <View style={[styles.terminal, { backgroundColor: "#0B0F13", borderColor: colors.border }]}><View style={styles.terminalBar}><Text style={{ color: "#35D07F", fontSize: 11, fontWeight: "700" }}>{profile.name} • bash</Text><Text style={{ color: running ? "#FFB547" : colors.muted, fontSize: 10 }}>{running ? "RUNNING" : connected ? "LIVE" : "OFFLINE"}</Text></View><View style={styles.output}>{lines.map((line, index) => <Text selectable key={index} style={[styles.line, { color: line.tone === "command" ? "#4DA3FF" : line.tone === "error" ? "#FF5C70" : line.tone === "system" ? "#35D07F" : colors.foreground }]}>{line.text}</Text>)}</View><View style={[styles.commandRow, { borderTopColor: colors.border }]}><Text style={{ color: "#35D07F", fontWeight: "800" }}>$</Text><TextInput editable={connected && !running} value={command} onChangeText={setCommand} onSubmitEditing={run} returnKeyType="send" placeholder={connected ? "Type a command…" : "Connect first"} placeholderTextColor="#586574" autoCapitalize="none" autoCorrect={false} style={[styles.commandInput, { color: colors.foreground }]} /></View></View>
    <View style={styles.toolRow}>{["CTRL+C", "TAB", "↑", "↓", "CLEAR"].map((tool) => <Pressable key={tool} onPress={() => { if (tool === "CLEAR") setLines([]); else if (tool === "CTRL+C") setCommand(""); else setCommand((old) => old + (tool === "TAB" ? "\t" : tool === "↑" ? "↑" : "↓")); }} style={({ pressed }) => [styles.tool, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.6 : 1 }]}><Text style={{ color: colors.muted, fontSize: 10, fontWeight: "800" }}>{tool}</Text></Pressable>)}</View>
  </ScrollView></KeyboardAvoidingView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 32 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }, kicker: { fontSize: 11, fontWeight: "800", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "800", marginTop: 6 }, connection: { borderRadius: 18, paddingHorizontal: 11, paddingVertical: 8, flexDirection: "row", gap: 7, alignItems: "center" }, dot: { width: 7, height: 7, borderRadius: 4 }, session: { borderRadius: 20, borderWidth: 1, padding: 16, marginBottom: 15 }, sessionTop: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 17 }, sessionIcon: { width: 38, height: 38, borderRadius: 12, alignItems: "center", justifyContent: "center" }, flex: { flex: 1 }, sessionName: { fontSize: 14, fontWeight: "800" }, sub: { fontSize: 10, marginTop: 4 }, stage: { minHeight: 42, flexDirection: "row", alignItems: "center", gap: 10 }, stageLine: { position: "absolute", width: 2, height: 42, left: 11, top: 22 }, stageIcon: { width: 24, height: 24, borderRadius: 12, borderWidth: 1, alignItems: "center", justifyContent: "center", zIndex: 1 }, stageTitle: { fontSize: 12, fontWeight: "700" }, close: { height: 42, borderRadius: 13, borderWidth: 1, alignItems: "center", justifyContent: "center", marginTop: 13 }, terminal: { borderRadius: 18, borderWidth: 1, overflow: "hidden", minHeight: 340 }, terminalBar: { padding: 12, borderBottomWidth: 1, borderBottomColor: "#252D37", flexDirection: "row", justifyContent: "space-between" }, output: { padding: 14, gap: 8, flex: 1, minHeight: 240 }, line: { fontSize: 12, fontFamily: "monospace", lineHeight: 18 }, commandRow: { borderTopWidth: 1, minHeight: 54, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 8 }, commandInput: { flex: 1, fontFamily: "monospace", fontSize: 13 }, toolRow: { flexDirection: "row", gap: 6, marginTop: 10 }, tool: { flex: 1, borderRadius: 9, borderWidth: 1, alignItems: "center", paddingVertical: 10 } });
